### ISSUE TITLE
Eliminar métodos de Feature de la fachada del mapa

### ISSUE THREAD

**Issue by manmorjim** [sigcorporativo-ja/Mapea4#107]
En la interfaz de la fachada de `M.Map` existen los métodos:

- `getFeatureCenter(): ol.Feature`

- `removeFeatureCenter(): void`

Estos métodos hacen referencia a clases de la librería base ol por lo que deberían eliminarse de la interfaz de la fachada de `M.Map` ya que va en contra de la filosofía de independizar la fachada de las librerías base en las que se apoya.

**Comment by fbma** [comment]
A partir de la v4.1, el feature es de tipo M.Feature
