### ISSUE TITLE
El control Navtoolbar no se visualiza

### ISSUE THREAD

**Issue by fbaena77** [sigcorporativo-ja/Mapea4#109]
Al añadir el control Navtoolbar (http://mapea4-sigc.juntadeandalucia.es/doc/M.control.Navtoolbar.html) de cualquiera de las formas posibles no se visualiza sobre el mapa.

http://jsfiddle.net/fbaena/utwt7L86/16/

**Comment by sigcorporativo-ja** [comment]
Buenas, ese control realmente existe heredado de versiones anteriores donde para navegar por el mapa (desplazando con pan, haciendo zoom con click, etc.) hacía falta activar explícitamente dicho control, se mantiene por retrocompatibilidad en el api.

Con Mapea4, esa navegación está activa por defecto, por lo que no hace falta añadirlo.

**Comment by fbaena77** [comment]
Muchas gracias!
