### ISSUE TITLE
Método addPlugins para añadir múltiples plugins

### ISSUE THREAD

**Issue by manmorjim** [sigcorporativo-ja/Mapea4#110]
Habría que añadir un método para poder añadir múltiples plugins en una llamada para seguir la misma filosofía de controles y capas. Se propone el método `addPlugins` que reciba un Array de plugins. Ejemplo:

En vez de:
```javascript
M.map("miDiv")
.addPlugin(new M.plugin.Geosearchbylocation())
.addPlugin(new M.plugin.Measurebar())
.addPlugin(new M.plugin.Streetview());

```
sería:
```javascript
M.map("miDiv")
.addPlugins([
  new M.plugin.Geosearchbylocation(),
  new M.plugin.Measurebar(),
  new M.plugin.Streetview()
]);

```

Valorar si se debería mantener el método `addPlugin` o marcarlo como deprecated.

**Comment by fbma** [comment]
Implementado en v6.3.0
