### ISSUE TITLE
Normalización de atributos para todas las capas

### ISSUE THREAD

**Issue by manmorjim** [sigcorporativo-ja/Mapea4#112]
Se propone normalizar y refactorizar los atributos de las capas en Mapea en función de su tipo. Los cambios propuestos serían los siguientes:

1. Debido a que todas las capas de Mapea son susceptibles de aparecer en el control `layerswitcher` con su leyenda asociada, la clase base `M.Layer` de las que heredan todas las capas debería incorporar el atributo `legend` evitando así que tenga que definirse en cada una de sus clases hijas. Además, siguiendo la filosofía de OpenLayers, se propone renombrar este atributo a `title` siendo más evocador este nombre para su función.

2. A su vez, se propone cambiar el atributo `name` a `id` puesto que se usa como identificador de la capa.

3. El atributo `transparent` es un atributo característicos de capas rasters y no tiene sentido, por ejemplo, para capas vectoriales. Es por ello que debería eliminarse de la clase `M.Layer`.

4. El atributo `extent` debería pertenecer a todas las capas por lo que se propone añadirlo a la clase `M.Layer`.

5. Se propone también hacer todos los atributos privados, siendo modificables y accesibles únicamente a través de sus métodos get/set correspondientes.

**Comment by fbma** [comment]
1.- Ya implementado
2.- Se añadió atributo interno id, conviviendo con name, que seguirá siendo el nombre de la capa.
3.- Se mantiene para especificar si una capa vectorial debe ser base (por ej. MVT).
4.- Atributos maxExtent_ y userMaxExtent existen ya en M.Layer
