### ISSUE TITLE
Error limpiar plugin searchstreet

### ISSUE THREAD

**Issue by jgleal** [sigcorporativo-ja/Mapea4#113]
Si Mapea se encuentra dentro de un formulario, al pulsar sobre el botón de limpiar (la 'X') en el plugin de SearchStreet, se recarga todo el mapa y en ocasiones aparece un error

http://jsfiddle.net/sigcJunta/jjrwz4sa/

**Comment by sigcorporativo-ja** [comment]
corregido en https://github.com/sigcorporativo-ja/Mapea4/pull/153
