### ISSUE TITLE
M.dialog pueda especificar el mapa en el que mostrarse

### ISSUE THREAD

**Issue by sigcorporativo-ja** [sigcorporativo-ja/Mapea4#120]
Actualmente, el uso M.dialog trabaja internamente [con la primera instancia de 'div.m-mapea-container' que encuentre](https://github.com/sigcorporativo-ja/Mapea4/blob/master/mapea-js/src/facade/js/dialog.js#L27), dando por sentado que existe únicamente un mapa en la página.

Sería mejor que su método M.dialog.show recibiera el objeto o el identificador del div donde mostrarse, permitiendo esto tener una aplicación varios mapas en un mismo html (algo común en apps móviles), y llevar una gestión más fina de sus diálogos.

**Comment by jgleal** [comment]
Mejor que en el mapa, se podrá especificar el contenedor padre, para dar más versatilidad al Dialog
