### ISSUE TITLE
M.evt.UNSELECT_FEATURES se lanza sin feature seleccionado

### ISSUE THREAD

**Issue by sigcorporativo-ja** [sigcorporativo-ja/Mapea4#121]
Cuando hay una capa WFS cargada, y se pincha en el mapa, se lanza siempre el evento M.evt.UNSELECT_FEATURES, aunque no hubiera ningún feature seleccionado.

Parece que ese lanzamiento se realiza en el [featureshandler](https://github.com/sigcorporativo-ja/Mapea4/blob/master/mapea-js/src/impl/ol/js/handlers/featureshandlers.js#L56), se debería comprobar antes de lanzarse si hay o no feature seleccionado.

**Comment by fbma** [comment]
Además, si hay seleccionado un feature y se selecciona otro pinchándolo, además del evento M.evt.SELECT_FEATURES asociado al nuevo, que sí se lanza, debiera lanzarse previamente otro de tipo M.evt.UNSELECT_FEATURES asociado al primer feature, que deja de estar seleccionado.

**Comment by fbma** [comment]
Con la 4.1, ha cambiado la localización de este lanzamiento, que se realiza ahora desde la fachada: https://github.com/sigcorporativo-ja/Mapea4/blob/master/mapea-js/src/facade/js/handlers/featureshandler.js#L83
