### ISSUE TITLE
Cambio de zoom al cambiar contexto

### ISSUE THREAD

**Issue by jgleal** [sigcorporativo-ja/Mapea4#124]
Al realizar un cambio de contexto, el mapa va alejándose con cada cambio

**Comment by sigcorporativo-ja** [comment]
Parece ocurrir solo en algunos niveles de zoom. Se puede reproducir con los contextos cdau y cdau_satelite, que tienen el mismo maxExtent y capas base con mismos MinScaleDenominator y MaxScaleDenominator.
