### ISSUE TITLE
add / remove KML

### ISSUE THREAD

**Issue by jgleal** [sigcorporativo-ja/Mapea4#14]
Cuando se añade una capa KML, se elimina, y se vuelve a añadir, el popup no aparece.

Reproducción del error: http://jsfiddle.net/leal33/qgcL25fh/

**Comment by fbma** [comment]
Se ha detectado que unque se soluciona el error, no retira el popup al hacer removeKML, por lo que sobre todo en interfaz móvil, queda uno encima de otro.
