### ISSUE TITLE
selectFeatures a fachada

### ISSUE THREAD

**Issue by jgleal** [sigcorporativo-ja/Mapea4#144]
Tras disponer de los features en fachada, habría que migrar a la misma el método de selección de los mismos:
https://github.com/sigcorporativo-ja/Mapea4/blob/master/mapea-js/src/impl/ol/js/layers/geojson.js#L149

Estudiar también si debería generalizarse este método (y relacionados) a todo capa Vector.

**Comment by fbma** [comment]
Actualmente la selección de features se realiza desde la clase FeatureHandler
