### ISSUE TITLE
Búsquedas con números en el nombre de vía

### ISSUE THREAD

**Issue by jgleal** [sigcorporativo-ja/Mapea4#146]
El pluguin searchStreet está parseando mal la búsqueda cuando el nombre de la vía tiene números. Por ejemplo con "Calle 28 de Febrero":

http://ws079.juntadeandalucia.es/EXT_PUB_CallejeroREST/geocoderMunProvSrs?streetname=CALLE&streetNumber=28&streetType=&municipio=Roquetas%20de%20Mar&provincia=almer%C3%ADa&srs=EPSG%3A25830

**Comment by fbma** [comment]
Ejemplo actualizado a ws248: "Calle 28 de Febrero"

https://ws248.juntadeandalucia.es/EXT_PUB_CallejeroREST/geocoderMunProvSrs?streetname=CALLE&streetNumber=28&streetType=&municipio=Alanís&provincia=Sevilla&srs=EPSG:25830&callback=mapea_jsonphandler_11284915402081575

**Comment by fbma** [comment]
Se concluyó que el problema de base se encuentra en el WS del Normalizador, ya que su respuesta incluye ya mal el nombre como portal.
