### ISSUE TITLE
Control de vuelta a norte

### ISSUE THREAD

**Issue by jgleal** [sigcorporativo-ja/Mapea4#174]
Cuando en móvil se gira el mapa, es complicado volver a dejarlo con el norte situado, por lo que estaría bien incorporar un control para tal fin.
También sería interesante poder deshabilitar dicha rotación y poder establecerla, para así poder hacerla dinámica usando los datos de la brújula cuando se empaquete en apps

**Comment by fbma** [comment]
El control 'rotate', disponible en la v5.1.0, ofrece la posibilidad de recentrado del norte al pinchar en el mismo
