### ISSUE TITLE
Carga de plugins dependiendo de la versión

### ISSUE THREAD

**Issue by jgleal** [sigcorporativo-ja/Mapea4#182]
Hay que estudiar la forma de que sea transparente al usuario las versiones de plugins soportadas por la versión de mapea utilizada. Es decir, habría que crear un único punto de entrada para cada plugin que fuera el que se encargará, pasada la versión de mapea usada, qué versión de plugin devolver al cliente.

**Comment by fbma** [comment]
v6.0.0 resourcePlugins
