### ISSUE TITLE
No se visualiza flecha para ocultar resultados plugin searchstreetgeosearch

### ISSUE THREAD

**Issue by callejerodeandalucia** [sigcorporativo-ja/Mapea4#195]
El botón que oculta el cuadro de texto y resultados de la búsqueda de calles usando el plugin searchstreetgeosearch [1] no se visualiza.

![image](https://user-images.githubusercontent.com/15340216/38862123-6c2002e8-4234-11e8-9870-3c73bad85d16.png)

[1] [http://mapea4-sigc.juntadeandalucia.es/?searchstreetgeosearch](http://mapea4-sigc.juntadeandalucia.es/?searchstreetgeosearch)

**Comment by fbma** [comment]
Se ha reproducido en Chrome 65.0.3325.181, no se reproduce en Firefox.

Parece un problema del z-index, con un valor superior a 99 se deja de ver. Afecta también a searchstreet, ya que ambos comparte estilo en el css:

https://github.com/sigcorporativo-ja/Mapea4/blob/e5e6cac7ef0df544230d7f926ac3d8e8d0e82277/mapea-js/src/plugins/geosearch/facade/assets/css/geosearch.css#L401
