### ISSUE TITLE
Estilo capa multigeometría

### ISSUE THREAD

**Issue by jgleal** [sigcorporativo-ja/Mapea4#205]
Actualmente la clase M.style.Simple es abstracta. Esto impide poder instanciar y crear un estilo para una capa multi-geometría.
Por tanto, es imprescindible poder instanciarla y que la misma englobe los elementos comunes a un estilo simple como fill, stroke o label.

**Comment by fbma** [comment]
Se implementa el estilo M.style.Generic en la v6.1.0
