### ISSUE TITLE
Opción responsive de complemento searchstreet

### ISSUE THREAD

**Issue by sigdeletras** [sigcorporativo-ja/Mapea4#207]
Hola,

Al embeber la dirección de un visor de Mapea4 en la web, el complemento searchstreet sale desplegado por defecto y oculta el control del gestor de capas. Tampoco permite cerrarlo.

Puede verse un ejemplo en la siguiente dirección [http://www.sigdeletras.com/2018/QGIS2Mapea4-plugin-qgis-para-crear-visores-web-con-datos-de-andalucia/](http://www.sigdeletras.com/2018/QGIS2Mapea4-plugin-qgis-para-crear-visores-web-con-datos-de-andalucia/)

Un saludo y felicidades por el trabajo

**Comment by fbma** [comment]
Gracias por el reporte, marcamos este issue como bug. Esta llamada reproduce el error del solape cuando se tiene el navegador con ancho suficientemente pequeño como para activar la interfaz móvil:

   http://mapea4-sigc.juntadeandalucia.es/?searchstreet=41091&controls=layerswitcher

El solape ocurre cuando se usa el complemento searchstreet especificando un municipio, ya que esto añade una sección adicional de texto que hace el control más alto.

Por otro lado, actualmente la interfaz de móvil del complemento searchstreet no permite cerrarlo, es el comportamiento normal, pero abrimos un issue como mejora para plantear que su funcionamiento sea como el del TOC: un botón que al pincharlo abra o cierre la interfaz de búsqueda.

**Comment by sigdeletras** [comment]
Estupendo. Estaré atento
Un saludo

**Comment by fbma** [comment]
Solucionado en la v5.0.0 de Mapea.
* https://mapea4-sigc.juntadeandalucia.es/assets/css/mapea-5.0.0.ol.min.css
* https://mapea4-sigc.juntadeandalucia.es/js/mapea-5.0.0.ol.min.js
* https://mapea4-sigc.juntadeandalucia.es/js/configuration-5.0.0.js
* https://mapea4-sigc.juntadeandalucia.es/plugins/searchstreet/searchstreet-2.0.0.min.css
* https://mapea4-sigc.juntadeandalucia.es/plugins/searchstreet/searchstreet-2.0.0.ol.min.js

**Comment by sigdeletras** [comment]
Muchas gracias por los enlaces
