### ISSUE TITLE
Conflicto en el resultado de las búsquedas de calles

### ISSUE THREAD

**Issue by callejerodeandalucia** [sigcorporativo-ja/Mapea4#212]
En determinadas ocasiones el resultado de la búsqueda de calles muestra una provincia que no se corresponde con el municipio al que pertenece la vía encontrada.

![image](https://user-images.githubusercontent.com/15340216/42631519-ba3b0d12-85da-11e8-9c3e-e966b7f78a08.png)

Al insertar una cadena de búsqueda en la que el municipio no coincide exactamente con uno existente el componente de búsqueda lanza una petición por cada provincia andaluza a la espera de obtener un resultado.

Parece ser que en determinadas circunstancias se interpretan mal las respuestas a esas peticiones y se establece una provincia errónea. 

Se ha detectado por ejemplo al hacer doble clic en la lupa de búsqueda, hacer clic antes de que devuelva el resultado la búsqueda anterior.

Se ha detectado tanto en el _plugin_ _searchstreet_ como en el _geosearchstreet_.

**NOTA:**

Se ha comprobado que el resultado de los servicios web de _CDAU_ no influye en este comportamiento (los métodos _geocoder_ no devuelven la provincia) aunque sí se va a proceder a corregir ciertos detalles que hacen salir a relucir este problema.
Nos referimos al método _normalizar_, que al recibir la provincia entre paréntesis la ignora y no la interpreta como tal, devolviéndola como complemento en su lugar.
Es por ello por lo que vamos a proceder a modificar dicho comportamiento.

**Comment by PabloIECA** [comment]
Este comportamiento, lleva reportado más de un año y no hay respuesta. El problema sigue ocurriendo: si se vuelve a pulsar la lupa antes de que se carguen todos los datos se muestra una provincia errónea. ¿Se tiene intención de proponer una solución?

**Comment by fbma** [comment]
Corregido v5.2.0, plugins searchstreet v2.0.1 y searchstreetgeosearch v2.0.2
