### ISSUE TITLE
[Handlebars] Compilación plantilla con helper adicional

### ISSUE THREAD

**Issue by jgleal** [sigcorporativo-ja/Mapea4#228]
Compilación de plantilla con mapea4 (correcto): http://jsfiddle.net/jgleal/L5aqvs0z/8
Mapea5: mismo código, misma plantilla, resultado vacío: http://jsfiddle.net/jgleal/L5aqvs0z/10

**Comment by emrivero** [comment]
Buenas, hemos visto que el problema viene de pasar los helpers a ES6. Suponemos que se pierde el scope this de las variables que se le pasa para compilar y falla. Ya lo hemos subsanado en develop.
