### ISSUE TITLE
[Handlebars] Exponer Handlebars

### ISSUE THREAD

**Issue by jgleal** [sigcorporativo-ja/Mapea4#229]
Para poder ampliarlo con más helpers u otras características, sería recomendable exportar Hadlebars (M.template) para así tenerlo accesible

**Comment by emrivero** [comment]
Buenas, echando un vistazo he comprobado que si se está exponiendo la libreria con la variable global 'Handlebars' así que en principio se podría cerrar esta issue.

**Comment by jgleal** [comment]
ok, ya lo vi. pues cancelo petición.
