### ISSUE TITLE
displayInLayerSwitcher en constructor

### ISSUE THREAD

**Issue by jgleal** [sigcorporativo-ja/Mapea4#235]
Actualmente existe el método displayInLayerSwitcher para hacer que una capa aparezca o no en la leyenda, pero habría que tener también esta posibilidad en el constructor de la capa, al estilo:

capa = new M.layer.WMS({
  url: 'http://capa',
  name: 'nombre',
  transparent: true,
  tiled: true,
  **displayInLayerSwitcher: false**
});

**Comment by emrivero** [comment]
Esto ya es posible haciendo
```
capa = new M.layer.WMS({
url: 'http://capa',
name: 'nombre',
transparent: true,
tiled: true,
}, {
displayInLayerSwitcher: false
});
