### ISSUE TITLE
Los controles de los plugins no están en el scope de window

### ISSUE THREAD

**Issue by emrivero** [sigcorporativo-ja/Mapea4#250]
En Mapea 4, al importart el minificado de los plugins se tenía acceso tanto al M.plugin.Plugin como a M.control.Plugin y M.impl.control.Plugin.

En Mapea 5 no es así, solo se tiene acceso a M.plugin.Plugin. Sería necesario definir si este comportamiento es adecuado o si deberíamos implementar el mismo mecanismo que tiene el core, donde el JSDoc dicta que clases y funciones se exportan como publicas para ser usadas y cuales no. Sobre todo para ser coherentes con respecto a la mejora del Arquetipo de plugins.

**Comment by fbma** [comment]
En principio los controles de un plugin no tienen por qué instanciarse fuera del mismo, por lo que no debe suponer un problema,
