### ISSUE TITLE
Error en M.plugin.Measurebar

### ISSUE THREAD

**Issue by emrivero** [sigcorporativo-ja/Mapea4#252]
http://mapea4-sigc.juntadeandalucia.es/?measurebar&layers=OSM&projection=EPSG:4326*d

Al medir distancias y calcular áreas en las proyecciones 4326 y 4258 (las dos utilizan degrees) los resultados no son correctos. El error suele ser de 10^4 unidades.

**Comment by fbma** [comment]
v5.2.0
