### ISSUE TITLE
[Scaleline] Muestra mal la distancia en 4326

### ISSUE THREAD

**Issue by gdtel-cnig-develop** [sigcorporativo-ja/Mapea4#264]
http://mapea4-sigc.juntadeandalucia.es/mapea/?controls=scaleline,panzoombar&layers=OSM&projection=EPSG:4326*d

No se ha probado con otras proyecciones

**Comment by fbma** [comment]
Aclaración: el error se produce con la herramienta measure bar:
http://mapea4-sigc.juntadeandalucia.es/mapea/?controls=scaleline,panzoombar,measurebar&layers=OSM&projection=EPSG:4326*d

**Comment by fbma** [comment]
v5.2.0
