### ISSUE TITLE
Error de impresión con formato JPG

### ISSUE THREAD

**Issue by emrivero** [sigcorporativo-ja/Mapea4#270]
Al imprimir el mapa base del callejero de Andalucia en jpg los colores salen distorsionados.
En mi caso, el tono de color mayoritario de la impresión es rosa.
http://jsfiddle.net/sigc_guadaltel/3kn1n1zn/

![mapea_2019-07-08_092626](https://user-images.githubusercontent.com/30650412/60791422-ef4ac600-a163-11e9-96a1-d54e70d2dd1b.jpg)

**Comment by fbma** [comment]
Este problema está ya reportado, es realmente una cuestión de la instancia de Geoprint, no de Mapea, ya que se puede reproducir desde la página de impresión de pruebas de Geoprint. 

Cierro este issue por ello, lo llevaremos desde la gestión de errores de Geoprint.
