### ISSUE TITLE
Evento al cerrar un popup

### ISSUE THREAD

**Issue by migueljabugo** [sigcorporativo-ja/Mapea4#291]
Seria útil que existiera un evento que detectase cuando se cierra un popup

**Comment by fbma** [comment]
Lo registramos como mejora. Actualmente se puede capturar el evento M.evt.DESTROY del popup del mapa, que se lanza cuando se cierra, el problema de este enfoque es que el objeto popup se crea dinámicamente cuando se usa, como por ejemplo al seleccionar features. 

```
capaVectorial.on(M.evt.SELECT_FEATURES, function(features, evt) {
  let popup = mapajs.getPopup();
  popup.on(M.evt.DESTROY, function() {
    console.log('Popup cerrado');
  });
});
```

El nuevo evento debería lanzarse sin necesidad de hacer seguimiento al objeto.

**Comment by fbma** [comment]
implementado v6.2.0  #399
