### ISSUE TITLE
Evento M.evt.LOAD en capas GeoJSON locales

### ISSUE THREAD

**Issue by fbma** [sigcorporativo-ja/Mapea4#308]
Si se crea una capa GeoJSON local, ya sea vacía o con features, para añadirle a continuación features, hay que esperar a que se dispare el evento M.evt.LOAD. Esto no debiera ser necesario, ya que no se está esperando respuesta asincrona de servicio externo.

**Comment by cristinaariza** [comment]
Hasta donde se ha visto, el feature no se puede añadir porque la capa de ol no existe aún:
` redraw() {
    const olLayer = this.getOL3Layer();  // <== AQUI DA NULL
    if (!isNullOrEmpty(olLayer)) {
      const style = this.facadeVector_.getStyle();
      let olSource = olLayer.getSource();
      if (olSource instanceof OLSourceCluster) {
        olSource = olSource.getSource();
      }

      if (style instanceof StyleCluster) {
        style.getImpl().deactivateChangeEvent();
      }

      // remove all features from ol vector
      const olFeatures = [...olSource.getFeatures()];
      olFeatures.forEach(olSource.removeFeature, olSource);

      const features = this.facadeVector_.getFeatures();
      olSource.addFeatures(features.map(Feature.facade2OLFeature));

      if (style instanceof StyleCluster) {
        style.getImpl().activateChangeEvent();
      }
    }
  }`

clase vector (impl) pasar this.ol3Layer = new OLLayerVector(this.vendorOptions_);
(l 93) al constructor

Se plantea solución:
` /**
   * This function sets the map object of the layer
   *
   * @private
   * @function
   */
  updateSource_() {
    if (isNullOrEmpty(this.vendorOptions_.source)) {
      this.requestFeatures_().then((features) => {
        if (this.ol3Layer) {
          this.ol3Layer.setSource(new OLSourceVector({
            loader: (extent, resolution, projection) => {
              this.loaded_ = true;
              // removes previous features
              this.facadeVector_.clear();
              this.facadeVector_.addFeatures(features);
              this.redraw();
              this.fire(EventType.LOAD, [features]);
            },
          }));
        }
        this.facadeVector_.addFeatures(features);
      });
    }
  }`

**Comment by fbma** [comment]
Es posible añadir un feature a una capa GeoJSON local sin esperar a que esta dispare el evento COMPLETED desde la v6.7.0
