### ISSUE TITLE
Error al cambiar de proyección (de 4326 a 3857)

### ISSUE THREAD

**Issue by carmenmarquez** [sigcorporativo-ja/Mapea4#336]
Si un mapa está configurado en 4326, se realiza algún movimiento y se cambia la proyección a 3857 se produce un error:
El formato del parámetro maxExtent no es correcto

Ejemplo de mapa:
map = map({
  container: 'map',
  layers: ['OSM'],
  projection: 'EPSG:4326*d'
});

Al llamar al setProjection entra en el método setBbox del facade/js/map con un bbox de [-18338414.503003035, NaN, 21736602.182575453, NaN]

Ese valor se genera desde el método setProjection impl/ol/js/Map:
const newBbox = ImplUtils.transformExtent(prevBbox, olPrevProjection, olProjection); => [-18338414.503003035, NaN, 21736602.182575453, NaN]

**Comment by fbma** [comment]
No logro reproducirlo con Mapea v6.1.0, ¿podéis confirmar si sigue ocurriendo?

1. Crear mapa:
```
map = new M.map({
container: 'map',
layers: ['OSM'],
projection: 'EPSG:4326*d'
});
```
2. Navegar por el mapa.
3. Cambiar projection:
```
map.setProjection("EPSG:3857*m");
```

**Comment by carmenmarquez** [comment]
Hola,
sí, sigue ocurriendo.
El paso 2 que es navegar por el mapa en realidad hay que pinchar en el mapa y mover el ratón.
Luego hay que hacer el setProjection.
Me he montado un ejemplo en codepen: https://codepen.io/carmenmarquez/pen/XWzJyJp
Un saludo

**Comment by fbma** [comment]
#399
