### ISSUE TITLE
Flexibilizar gestión de niveles de zoom en Mapea

### ISSUE THREAD

**Issue by dlunar29** [sigcorporativo-ja/Mapea4#351]
Actualmente en Mapea se trabaja exclusivamente con 16 niveles de zoom

En algunos casos se requiere incorporar más niveles por lo que se debe flexibilizar de alguna manera.

Una solución inicial rápida puede ser la de incrementar el valor actual pero de entrada se ha detectado que ese valor aparece en uso en diferentes partes de código sin hacer uso de una constante. De entrada se debería establecer el valor del zoomLevels en ciertos métodos inicializándolos al valor de una constante por defecto.

En cualquier caso, la solución debe pasar por habilitar un mecanismo para poder crear el mapa con los niveles que requiera el usuario.

* Map.js
<pre>
updateResolutionsFromBaseLayer
// zoom levels
let zoomLevels = 16;
</pre>

* Layers
<pre>
 getNumZoomLevels() {
    return 16; // 16 zoom levels by default
  }
</pre>
* Tile.js
<pre>
getZoomLevels() {
let zoomLevels = 16;
...
</pre>
* WMS
<pre>
if (isNullOrEmpty(this.options.numZoomLevels)) {
      this.options.numZoomLevels = 16; // by default
    }
</pre>
* OSM

Como parche inicial para aplicaciones que requieran extender los niveles de zoom se pueden modificar las resoluciones de forma externa según el siguiente mecanismo:

> Por defecto mapea introduce 16 niveles de zoom a un mapa. Si se quiere aumentar los niveles de zoom se tendrá que regenerar las resoluciones del mapa una vez creada la instancia del mapa del siguiente modo:

<pre>
map.calculateMaxExtent().then((maxExtent) => {
  const size = map.getMapImpl().getSize();
  const zoomLevels = 20;
  const units = map.getProjection().units;
  const resolutions = M.utils.generateResolutionsFromExtent(maxExtent, size, zoomLevels, units);
  map.setResolutions(resolutions);
});
</pre>

**Comment by fbma** [comment]
implementado v6.2.0  #399
