### ISSUE TITLE
Posibilidad de cambiar el fondo transparente

### ISSUE THREAD

**Issue by emrivero** [sigcorporativo-ja/Mapea4#362]
Para ciertas capas y proyecciones, el mapa establece de fondo donde no hay datos cartográficos un color alfa o de transparencia:

![Captura de pantalla de 2021-04-13 17-12-50](https://user-images.githubusercontent.com/30650412/114576655-a0f12200-9c7b-11eb-8db9-7f4697016a3a.png)

Sería interesante poder establecer el color de fondo de manera personalizada:
![Captura de pantalla de 2021-04-13 17-15-14](https://user-images.githubusercontent.com/30650412/114577156-13620200-9c7c-11eb-9397-232ab88e1b18.png)
![Captura de pantalla de 2021-04-13 17-16-49](https://user-images.githubusercontent.com/30650412/114577195-1a891000-9c7c-11eb-90ca-8ad809a5c812.png)

**Comment by fbma** [comment]
implementado v6.2.0  #399
