### ISSUE TITLE
Plugin searchstreetgeosearch. Comportamiento confuso

### ISSUE THREAD

**Issue by PabloIECA** [sigcorporativo-ja/Mapea4#373]
Si escribimos y le damos a enter antes de que salgan los resultados de autocompletar. Parece que la búsqueda responde antes y el autocompletar responde después y el plugin los muestra según responden. Si escribimos y le damos tiempo al autcompletador a mostrar los resultados, todo funciona correctamente
![Captura de pantalla de 2021-11-23 11-33-04](https://user-images.githubusercontent.com/36229394/143008782-4f382e16-5445-43ed-be76-ca8b554e6a50.png)
.

**Comment by PabloIECA** [comment]
Como se puede ver en el pantallazo, la búsqueda del autocompletador aparece sobre los resultados. En el caso expuesto, no es problemático porque sólo hay un resultado, pero si hay muchos como es normal, tapan completamente los resultados.

**Comment by PabloIECA** [comment]
En relación con este plugin, también es ha detectado que el comportamiento es diferente según se pulse "enter" tras escribir o se piche sobre la lupa. En el primer caso, los resultados del autocompletar se quedan en pantalla y ocultan los resultados. Si pulsamos sobre la lupa, se ocultan los resultados del autocompletar y se pueden ver los resultados de la búsqueda.

**Comment by fbma** [comment]
Solucionado en la v2.1.0 del plugin
