### ISSUE TITLE
Error al obtener la leyenda de algunas capas con versión 1.3.0

### ISSUE THREAD

**Issue by carmenmarquez** [sigcorporativo-ja/Mapea4#400]
TEST: https://sigc-dev-ol.desarrollo.guadaltel.es/mapea6/?controls=navtoolbar,layerswitcher&wmcfile=mapa&layers=WMS*Redes*http://www.ideandalucia.es/wms/mta400v_2008?*Redes_energeticas*true

Muestra error por consola: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'Style') y no muestra la leyenda.

Se produce tras el cambio de que si la capa tiene versión 1.3.0 usa LegendURL y si es menor usa GetLegendGraphic.
Esto no ocurre con todas las capas, en la de redes (por ejemplo) devuelve una capa dentro de otra y se tendría que modificar el método para que si se da ese caso busque la capa también dentro de la capa que contiene capas.

**Comment by fbma** [comment]
Resuelto
