### ISSUE TITLE
Icono cierre popup movil

### ISSUE THREAD

**Issue by alb-martinez** [sigcorporativo-ja/Mapea4#421]
Estando en modo dispositivo movil, al seleccionar un punto sobre el mapa aparece la información del punto sobre un popup en la parte inferior de la pantalla. Dicho popup tiene como icono de cierre una flecha así > que lleva a confusión.
Segun el css es el icono "\e919". Habria que sustituirlo por el simbolo de la X que sería el "\2716", como está configurado para el popup cuando estamos en modo web.
![Mapea4_KML_JSFiddle_icono_popup](https://user-images.githubusercontent.com/37654975/230024711-1e2e8755-4181-4d19-b523-95647b39448f.png)
![Mapea4_KML_JSFiddle_css_iconos](https://user-images.githubusercontent.com/37654975/230025193-f7152bcf-daeb-46f6-80d0-7fbb0f708718.png)

**Comment by fbma** [comment]
v6.6.0
