### ISSUE TITLE
Bug con el ZOOM y clúster

### ISSUE THREAD

**Issue by enprava** [sigcorporativo-ja/Mapea4#458]
## Descripción

Al configurar ```M.config.ZOOM_LEVELS = 1000;``` y al tener un clúster con al menos dos puntos exactamente en la misma posición, al hacer clic en el clúster, se produce un error que resulta en un zoom incontrolable hasta una escala de 1:NaN. Esto hace que el mapa se vuelva completamente blanco y la única solución es recargar la página.

## Pasos para reproducir el problema

  Configurar ```M.config.ZOOM_LEVELS = 1000;```
  Crear un clúster con al menos dos puntos en la misma posición.
  Hacer clic en el clúster.

## Ambiente

Navegador y versión: ```Google Chrome Versión 122.0.6261.112```
Sistema operativo: ```Windows 11 Home 23H2```

## Capturas de pantalla

![imagen](https://github.com/sigcorporativo-ja/Mapea4/assets/56026581/47cef1ab-01bb-4b3e-acbc-5852fd9b323f)

**Comment by fbma** [comment]
No logramos reproducir el error, ¿podrías pasarnos el código con el que te ocurre?

Fiddle usando Mapea v6.6.0: https://jsfiddle.net/sigcJunta/aqz3L9bw/

**Comment by enprava** [comment]
No he logrado reproducir el error, siento mucho las molestias.
