### ISSUE TITLE
Formato imágen en capas WMTS

### ISSUE THREAD

**Issue by jgleal** [sigcorporativo-ja/Mapea4#48]
No hay ninguna forma de establecer el formato en el que solicitar las capas WMTS. Actualmente lo que está es leyendo los formatos posibles del capabilities y quedarse con el primero que encuentra.

**Comment by fbma** [comment]
Además, debería tener implementado el atributo 'transparent'.

**Comment by romanbamio** [comment]
Te refieres a WMTS ¿verdad?

**Comment by jgleal** [comment]
Editado. Gracias por avisar de la errata @romanbamio
