### ISSUE TITLE
Popup capa GeoJSON

### ISSUE THREAD

**Issue by jgleal** [sigcorporativo-ja/Mapea4#49]
En el popup se descuadran los campos, teniendo unos más margen a la izqda que otros.

**Comment by jgleal** [comment]
la plantilla escapa el html, modificarla para que esto no ocurra

**Comment by sigcorporativo-ja** [comment]
Aprovechar para ver si no tiene más sentido alinear el texto a la izquierda, como:

.m-popup>div.m-content>div.m-body>div.m-geojson-content>div.result>table td.kye {    text-align: left;}
