### ISSUE TITLE
Popup vacío con dos KML

### ISSUE THREAD

**Issue by jgleal** [sigcorporativo-ja/Mapea4#53]
Cuando se cargan dos capas KML, el popup (con el estilo de pantallas <768px) aparece en blanco.

http://jsfiddle.net/sigcJunta/v4xpkLne/

**Comment by jgleal** [comment]
El problema viene cuando se añaden dos capas con el mismo nombre, por tanto debería dar un error, y avisar al usuario, si se intenta esto.

**Comment by fbma** [comment]
Se cierra este issue, y el bug de capas con el mismo nombre se recoge en la issue #65
