### ISSUE TITLE
Varias capas en WMC con mismo 'name'

### ISSUE THREAD

**Issue by fbma** [sigcorporativo-ja/Mapea4#65]
Actualmente en un wmc solo puede estar definida una layer con un mismo atributo 'name', de haber más de una, en Mapea sólo se muestra una. Esto es porque dicho atributo representa el ID de la capa.

Pero en algunos escenarios, puede que se desee tener una misma capa de un mismo servidor WMS duplicada en el TOC. 

Habría que mirar:
- Si esto es posible según la especificación wmc
- En caso afirmativo, que internamente el ID de cada layer tuviera un valor único que permitiera el escenario planteado.

**Comment by emiliopardo** [comment]
¿como va este tema?

**Comment by fbma** [comment]
Este issue afecta a cualquier capa, no solo aquellas añadidas a través de un WMC.

**Comment by fbma** [comment]
Se renombra issue para que refleje que el efecto deseado es sobre las capas en general, no tienen por qué estar definidas en un wmc. Especialmente en las WMS, donde el atributo 'name' al hacer de id, impide cargar dos veces el mismo WMS, cosa que a veces tendría sentido si se cargan con estilos diferentes.

**Comment by fbma** [comment]
Implementado en v6.3.0
