### ISSUE TITLE
¿Deberían los plugins tener atributo name?

### ISSUE THREAD

**Issue by fbma** [sigcorporativo-ja/Mapea4#85]
Controlbase lo establece para los controles, que lo requieren en el constructor, lo que permite además hacer operaciones con los controles como:

```javascript
var control = mapajs.getControl({name:'layerswitcher'});
```  
¿Sería de utilidad que los plugins también lo tuvieran? y declarase en caso afirmativo en facade/plugin.js. Si no, suponiendo que queramos obtener un  plugin concreto desde el objeto mapa, ¿cómo lo obtendríamos partiendo del mapajs.getPlugins() actual?

**Comment by jgleal** [comment]
Sí sería recomendable, pero debe ir acompañado de una homogeneización de la forma de filtrado, ya que el método `getPlugins` acepta únicamente el/los nombre/s, no como en el resto de filtrados donde se le pasa un objeto con {clave: 'valor'}

**Comment by fbma** [comment]
Se ha añadido el atributo name al arquetipo de plugin de la herramienta mapea-create-plugin
