### ISSUE TITLE
Leer <ol:maxExtent> a nivel de capas en los wmc

### ISSUE THREAD

**Issue by sigcorporativo-ja** [sigcorporativo-ja/Mapea4#89]
Actualmente se lee el <ol:maxExtent> global del wmc, pero las layer podrían tener definido uno propio. En ese caso, el parseador wmc debería leerlo y asignar los valores correspondientes al maxExtent de la layer.

Esta mejora está ligada a la #79.

**Comment by fbma** [comment]
En la v5.0.0 se lee el max y el minExtent propio de cada capa que lo tenga y se les asigna para que apliquen en base al algoritmo de gestión de las extensiones máximas y mínimas en Mapea. 
Ejemplo: capa 'batimetria' en http://mapea4-sigc.juntadeandalucia.es/mapea/files/wmc/mapa.xml
