### ISSUE TITLE
Compilación de plantillas en core

### ISSUE THREAD

**Issue by manmorjim** [sigcorporativo-ja/Mapea4#90]
Actualmente las plantillas Handlebars de los componentes del core son solicitadas por Mapea bajo demanda en tiempo de ejecución al servidor introduciendo así dos inconvenientes:
- Asincronismo dentro del código obligando a trabajar con Promises y eventos.
- Aumento del tiempo de carga puesto que para cada componente realiza una petición HTTP para solicitar la plantilla y compilarla.

Se debería trasladar el mecanismo de compilación de plantillas de _Mapea4-dev_ de los plugins al core, de forma que éstas estén disponibles desde JavaScript eliminando así los inconvenientes anteriormente citados.

**Comment by jgleal** [comment]
Se compilara la plantilla de cada plugin en su js y los controles en el core

**Comment by fbma** [comment]
Implementado en la v5.0.0
