### ISSUE TITLE
map.removeControls y map.removePlugin

### ISSUE THREAD

**Issue by jgleal** [sigcorporativo-ja/Mapea4#93]
Se ha detectado que, al eliminar un control del mapa mediante la función "removeControls", mapea intenta [eliminarlo de sus paneles](https://github.com/sigcorporativo-ja/Mapea4/blob/master/mapea-js/src/facade/js/map/map.js#L1335), pero si no está añadido a ningún panel, da error.

También, se observa que se [está llamando al método ](https://github.com/sigcorporativo-ja/Mapea4/blob/master/mapea-js/src/facade/js/map/map.js#L1810) "destroy" del plugin cuando se hace un "removePlugin", pero en el arquetipo del plugin no se crea dicho método.

**Comment by fbma** [comment]
Se lleva el issue del destroy al repositorio de Mapea4-dev, y se cierra este issue al haberse resuelto el problema del removeControls.
