### ISSUE TITLE
Mejora en la gestión del maxExtent

### ISSUE THREAD

**Issue by jgleal** [sigcorporativo-ja/Mapea4#96]
Es importante dotar a Mapea de una mejor gestión del maxExtent de las capas:

- Las capas deberán poder tener su maxExtent, opcional, con métodos get/set.
- El maxExtent deberá poder leerse del fichero WMC en caso de que se use uno, o el que tenga definido en su servicio WMS si no se lee de un WMC sino de un WMS.
- El mapa tendrá su propio maxExtent, vía asignación, vía leerlo del WMC.
- Si una capa no tiene maxExtent, le aplicaría el del mapa, que si no tiene explícito, sería el de su proyección.
- Esto es independiente de las max/minScales, que son las escalas/reosluciones que controlan su visibilidad.

**Comment by sigcorporativo-ja** [comment]
Relacionados:  #79 ##89

**Comment by manmorjim** [comment]
Por unificar términos haría como OpenLayers y manejaría únicamente dos conceptos dentro de Mapea: bbox y extent. De esta forma los parámetros y métodos quedarían:

 - `getExtent(): Array<Number>`
- `setExtent(Array<Number>): void`

Obviando así todas las referencias a `maxExtent` excepto en el constructor de `M.map` por mantener retrocompatibilidad.

**Comment by sigcorporativo-ja** [comment]
Entiendo que ok a nivel de api js, en los wmc se debería poder seguir usando <ol:maxExtent  por retrocompatiblidad, o admitir ambos. Los metodos actuales *maxExtent( se marcarían como deprecated.
